AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodePipeline to deploy ECS using CloudFormation'

Resources:
  # IAM Role for CodePipeline
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodePipelineCloudFormationRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [codepipeline.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStackEvents
                  - iam:PassRole
                Resource: "*"

  # AWS CodePipeline
  CloudFormationPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: <S3_BUCKET_NAME>  # Replace with your S3 bucket for storing artifacts
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket: <S3_BUCKET_NAME>  # Replace with actual bucket name
                S3ObjectKey: ecs-cloudformation.yml  # CloudFormation file
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Deploy
          Actions:
            - Name: DeployCF
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                StackName: MyECSStack
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                TemplatePath: SourceOutput::ecs-cloudformation.yml
              InputArtifacts:
                - Name: SourceOutput